name: Package the application and produce executable

on:
  push:
    tags:
      - '*'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: fail2ban_exporter

jobs:
  pypi_build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip build
          python -m pip install pipenv
      - name: Install project dependencies
        run: |
          make dependencies
      - name: Build a binary wheel and a source tarball
        run: |
          make build
      - uses: actions/upload-artifact@v2
        with:
          name: pypi-artifacts
          path: ./dist/
          
  pyinstaller_build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Update cache and install upx
        run: |
          sudo apt-get update
          sudo apt-get install upx
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
      - name: Install project dependencies
        run: |
          python -m pipenv install -d

      - name: Build executable
        run: |
          make package
      
      - name: Create an archive from the executable
        run: |
          tar -czvf fail2ban_exporter_executable-${{steps.tag.outputs.tag}}.tar.gz -C ./dist fail2ban_exporter
      - uses: actions/upload-artifact@v2
        with:
          name: fail2ban_exporter_executable
          path: ./fail2ban_exporter_executable-*.tar.gz
  release:
    needs: [pypi_build, pyinstaller_build]
    runs-on: ubuntu-latest
    steps:
      - name: Download pypi artifacts
        uses: actions/download-artifact@v2
        with:
          name: pypi-artifacts
      - name: Download executable artifact
        uses: actions/download-artifact@v2
        with:
          name: fail2ban_exporter_executable
      
      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            *.tar.gz
            *.whl

  docker_build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-qemu-action@v2

      - name: Set up Docker buildx 
        uses: docker/setup-buildx-action@v2.0.0

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/386
